image:
  repository: quay.io/zachglassman/jupyterhub-stress
  tag: v0.4.7
  pullPolicy: IfNotPresent
resources: {}

hub:
  url: "https://clustertest2.thedataincubator.co"

test:
  type: rw

users:
  count: 50